# fly.toml app configuration file generated for spacefarm-chatbot-app on 2025-08-23T20:20:22+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spacefarm-chatbot-app'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "chatbot_data"
  destination = "/data"
